version: "3.3"
services:
  portainer:
     image: portainer/portainer-ce:latest
     container_name: portainer
     environment:
       - TZ=Europe/Region
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /opt/portainer/portainer_data:/data
     ports:
       - 80:8000
       - 443:9443
     restart: always
